### ISSUE TITLE
Conda-forge package?

### ISSUE THREAD

**Issue by Zeitsperre** [taskipy/taskipy#56]
Hi,

Very neat package that adds a key missing functionality to pyproject.toml. Thanks for making this!

I'm wondering if you would be interested in contributing this package to the [conda-forge](https://conda-forge.org/) package index? I think this would be a great addition and would be useful for ensuring reproducible builds. Upkeep is very minimal (automation helps ensure that packages are kept up-to-date, with little effort required of maintainers).

If you are interested, I can help draft a recipe and/or maintain the conda-forge package if you'd like.

Best,

**Comment by illBeRoy** [comment]
Hey Trevor! That sounds like a great idea.
We've added it into our project plan. Would you be willing to contribute this? 🤩

**Comment by Zeitsperre** [comment]
Hi Roy,

For sure! I can stage a recipe for taskipy later today and mark you as a co-maintainer. Will link to this issue when the PR is ready in conda-forge.

Best,

**Comment by Zeitsperre** [comment]
Pull request for conda-forge is open: https://github.com/conda-forge/staged-recipes/pull/22761
