### ISSUE TITLE
Allow psutils >= 6.0

### ISSUE THREAD

**Issue by 4sfaloth** [taskipy/taskipy#84]
`psutils` does not provide pre-built binaries for macos up until 6.0. This makes it very relevant for MacOS users to be able to update to psutils >= 6.0, which is current blocked for taskipy's users (due to usage of ^5x in the `pytoml`)

**Comment by Zeitsperre** [comment]
Just an FYI, but this is the only blocking change for Python3.13 support on `conda-forge`.

**Comment by illBeRoy** [comment]
Hi!
Taking a look

**Comment by illBeRoy** [comment]
Released as 1.14.1 [see notes](https://github.com/taskipy/taskipy/releases/tag/1.14.1)

Please lmk that it works as expected, and I'll close this issue. Enjoy!

**Comment by LironEr** [comment]
That works for me, thank you! (:
